spring:
  application:
    name: Usuario
  datasource:
    url: jdbc:mysql://localhost:3303/usuarios?createDatabaseIfNotExist=true
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true       # opcional, para ver las queries en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
server:
    port: 8081