#spring.application.name=Gateway

server:
  port: 8080

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://localhost:3305/gateway?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true       # opcional, para ver las queries en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    gateway:
      mvc:
        routes:
          - id: usuario-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/usuarios/**
          - id: monopatin-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/monopatines/**
          - id: parada-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/paradas/**
          - id: viaje-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/viajes/**
          - id: chat-ia-service
            uri: http://localhost:8085
            predicates:
                - Path=/api/chat-ia/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"