#spring.application.name=Gateway

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/**
        - id: monopatin-service
          uri: http://localhost:8082
          predicates:
            - Path=/monopatines/**
        - id: parada-service
          uri: http://localhost:8083
          predicates:
            - Path=/paradas/**
        - id: viaje-service
          uri: http://localhost:8084
          predicates:
            - Path=/viajes/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
