version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: Usuario-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: usuarios
    ports:
      - "3303:3306"