spring:
  application:
    name: Cuenta
  datasource:
    url: jdbc:mysql://localhost:3307/cuentas?createDatabaseIfNotExist=true
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop  # crea/borra tablas autom?ticamente
    show-sql: true       # opcional, para ver las queries en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect