server:
  port: 8085   # o el que quieras

spring:
  application:
    name: chat-ia-service

groq:
  api-key: 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
  base-url: https://api.groq.com/openai
  model: llama-3.1-8b-instant
