spring:
  application:
    name: Viaje
  datasource:
    url: jdbc:mysql://localhost:3309/viajes?createDatabaseIfNotExist=true
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop  # (PONER UPDATE) edita tablas autom?ticamente
    show-sql: true       # opcional, para ver las queries en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
server:
  port: 8084