spring:
  application:
    name: Facturacion
  datasource:
    url: jdbc:mysql://localhost:3306/Facturacion?createDatabaseIfNotExist=true
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update  # crea/borra tablas autom?ticamente
    show-sql: true       # opcional, para ver las queries en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect