version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: Parada-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: paradas
    ports:
      - "3302:3306"